FROM    golang:1-alpine AS cli

RUN     apk add -U git bash coreutils gcc musl-dev

RUN mkdir -p /go/src/github.com/docker/ && \
    cd /go/src/github.com/docker/ && \
    git clone https://github.com/docker/cli.git && \
    cd cli && \
    git checkout v18.09.6

ENV     CGO_ENABLED=0 \
        DISABLE_WARN_OUTSIDE_CONTAINER=1

WORKDIR /go/src/github.com/docker/cli
RUN     ./scripts/build/binary && strip ./build/docker

FROM webvariants/nginx-acme-and-more

COPY --from=cli /go/src/github.com/docker/cli/build/docker /usr/local/bin/docker

COPY nginx-dconf /etc/nginx/

WORKDIR /etc/nginx

CMD ./nginx-dconf
