#!/bin/bash

if [ "$(id -u)" = "0" ]; then
  echo "do not run as root!"
  exit 1
fi

WORK_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"
BIN="$WORK_DIR/bin"
HAVE_MKCERT=$(which mkcert >/dev/null 2>&1;echo $?)
MKCERT_BIN="$BIN/mkcert"

if [ $HAVE_MKCERT -eq 1 -a ! -e "$MKCERT_BIN" ]; then
  mkdir -p "$BIN"
  curl -L "https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-linux-amd64" -o "$MKCERT_BIN"
  chmod +x "$MKCERT_BIN"
elif [ $HAVE_MKCERT -eq 0 ]; then
  MKCERT_BIN=$(which mkcert)
fi

CERTS="$WORK_DIR/certs"
HOST_FILES="/etc/hosts"

if [ -f ./hosts.export/hosts ]; then
    HOST_FILES="./hosts.export/hosts $HOST_FILES"
fi

NAMES=$(cat $HOST_FILES | grep -E "^127\.[0-9.]+\.[0-9.]+\.[0-9.]+[ \t]+" | sed -E "s/^127\.[0-9.]+[ \t]+(.+)#.*/\1/" | tr "[:space:]" "\n" | sort -u | tr "\n" " ")

mkdir -p "$CERTS"

"$MKCERT_BIN" -install

"$MKCERT_BIN" -cert-file="$CERTS/hosts.pem" -key-file="$CERTS/hosts-key.pem" $NAMES "localhost" "docker.localhost" "*.docker.localhost" "*.dev.docker.localhost"
