#!/bin/bash

if [ "$(id -u)" = "0" ] && [ "$1" != "force" ]; then
  echo "do not run as root!"
  exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")"

BIN="./bin"
HAVE_MKCERT=$(which mkcert >/dev/null 2>&1;echo $?)
MKCERT_BIN="$BIN/mkcert"

if [ $HAVE_MKCERT -eq 1 -a ! -e "$MKCERT_BIN" ]; then
  mkdir -p "$BIN"
  case "$OSTYPE" in
    solaris*) echo "SOLARIS is not supported!"; exit 1 ;;
    darwin*)  MKCERT_FILE=mkcert-v1.4.0-darwin-amd64 ;;
    linux*)   MKCERT_FILE=mkcert-v1.4.0-linux-amd64 ;;
    bsd*)     echo "BSD is not supported!"; exit 1 ;;
    msys*)    echo "WINDOWS is not supported!"; exit 1 ;;
    *)        echo "unknown: $OSTYPE"; exit 1 ;;
  esac
  curl -L "https://github.com/FiloSottile/mkcert/releases/download/v1.4.0/$MKCERT_FILE" -o "$MKCERT_BIN"
  chmod +x "$MKCERT_BIN"
elif [ $HAVE_MKCERT -eq 0 ]; then
  MKCERT_BIN=$(which mkcert)
fi

CERTS="./certs"
HOST_FILES="/etc/hosts"

if [ -f ./hosts.export/hosts ]; then
    HOST_FILES="./hosts.export/hosts $HOST_FILES"
fi

NAMES=$(cat $HOST_FILES | grep -E "^127\.[0-9.]+\.[0-9.]+\.[0-9.]+[ \t]+" | sed -E "s/^127\.[0-9.]+[ \t]+(.+)#.*/\1/" | tr "[:space:]" "\n" | sort -u | tr "\n" " ")

mkdir -p "$CERTS"

"$MKCERT_BIN" -install

"$MKCERT_BIN" -cert-file="$CERTS/hosts.pem" -key-file="$CERTS/hosts-key.pem" $NAMES "localhost" "docker.localhost" "*.docker.localhost" "*.dev.docker.localhost"
