#!/bin/bash

BIN="$(dirname $(realpath "${BASH_SOURCE[0]}"))/bin"

if [ ! -e "$BIN/mkcert" ]; then
  mkdir -p "$BIN"
  curl -L "https://github.com/FiloSottile/mkcert/releases/download/v1.2.0/mkcert-v1.2.0-linux-amd64" -o "$BIN/mkcert"
  chmod +x "$BIN/mkcert"
fi

CERTS="$(dirname $(realpath "${BASH_SOURCE[0]}"))/certs"

NAMES=$(cat /etc/hosts | grep -P "^127.\d+.\d+.\d+\s+" | sed -E "s/^127\.[0-9.]+[ \t]+(.+)#.*/\1/" | tr "[:space:]" "\n" | sort -u | tr "\n" " ")

mkdir -p "$CERTS"

"$BIN/mkcert" -install

"$BIN/mkcert" -cert-file="$CERTS/hosts.pem" -key-file="$CERTS/hosts-key.pem" $NAMES "localhost" "docker.localhost" "*.docker.localhost"
