#!/bin/bash -e

if [[ "$(docker images -q mycli 2> /dev/null)" == "" ]]; then
	echo "FROM debian:9-slim
RUN apt-get update  && apt-get -y install python-pip
RUN pip install -U mycli
RUN useradd -ms /bin/bash john
USER john
WORKDIR /home/john
ENTRYPOINT [\"mycli\"]" \
	| docker build --pull --force-rm --tag mycli -
fi

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

docker run \
	--rm \
	-ti \
	-e LC_ALL=C.UTF-8 \
	-e LANG=C.UTF-8 \
	--network mysql \
	mycli \
	-h mysql80 -u root -p$MYSQL_ROOT_PASSWORD $@
