#!/bin/bash

if [ ! -f $1 ]; then
	echo "$1 not a file"
	exit
fi

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

docker run \
	--rm \
	--read-only \
	-v $(realpath $1):/dump.sql:ro \
	--network mysql \
	-e "MYSQL_PWD=$MYSQL_ROOT_PASSWORD" \
	mysql:8.0 \
	/bin/bash -c "cat /dump.sql | mysql -h mysql80 -u root ${2}"
