#!/bin/bash

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

docker run \
	--rm \
	--read-only \
	-ti \
	--network mysql \
	mysql:8.0 \
	mysql -h mysql80 -u root -p$MYSQL_ROOT_PASSWORD $@
