#!/bin/bash

FILE=$(realpath $1)

if [ -f "$FILE" ]; then
    echo "File already exists."
    exit
fi

touch "$FILE"

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

docker run \
	--rm \
	--read-only \
	--link mysql \
	-v "$FILE:/dump.sql" \
	--network mysql \
	mysql:8.0 \
	/bin/bash -c "mysqldump -h mysql80 -u root -p$MYSQL_ROOT_PASSWORD ${2} > /dump.sql"
