#!/bin/bash

if [ ! -f $1 ]; then
	echo "$1 not a file"
	exit
fi

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

docker run \
	--rm \
	--read-only \
	-v $(realpath $1):/dump.sql:ro \
	--network mysql \
	mysql:5.7 \
	/bin/bash -c "cat /dump.sql | mysql -f -h mysql -u root -p$MYSQL_ROOT_PASSWORD ${2}"
