#!/bin/bash

FILE=$(realpath $1)

if [ -f "$FILE" ]; then
    echo "File already exists."
    exit
fi

touch "$FILE"

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

docker run \
	--rm \
	--read-only \
	--link mysql \
	-v "$FILE:/dump.sql" \
	--network mysql \
	-e "MYSQL_PWD=$MYSQL_ROOT_PASSWORD" \
	mysql:5.7 \
	/bin/bash -c "mysqldump -h mysql -u root ${2} > /dump.sql"
