#!/bin/bash

export $(cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env" | grep -v ^# | xargs)

if [ -t 0 ] && [ -t 1 ] ; then T=-t; else T=; fi # detect terminal

exec docker run $T -i \
	--rm \
	--read-only \
	--network mysql \
	-e "MYSQL_PWD=$MYSQL_ROOT_PASSWORD" \
	mysql:5.7 \
	mysql -h mysql -u root $@
