#!/bin/bash

if [ ! -f $1 ]; then
	echo "$1 not a file"
	exit
fi

docker run \
	--rm \
	--read-only \
	-v $(realpath $1):/dump.sql:ro \
	--network mysql \
	mysql:5.7 \
	/bin/bash -c "cat /dump.sql | mysql -h mysql -u root -proot ${2}"
