#!/bin/bash

docker pull "uifd/ui-for-docker"

docker run \
	--detach \
	--restart=always \
	--privileged \
	--volume="/var/run/docker.sock:/var/run/docker.sock" \
	--name="ui-for-docker" \
	$@ \
	"uifd/ui-for-docker"

# port 9000
