#!/bin/bash -e

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

SIZE=`cat /proc/meminfo | grep MemTotal | awk '{ print $2 $3 }'`
FILE=/swapfile

if [ -f $FILE ]; then
	echo "Swapfile $FILE already exists." 1>&2
	exit 1
fi

fallocate -l $SIZE $FILE
mkswap $FILE
chmod 600 $FILE
echo "$FILE none swap sw,pri=2 0 0" >> /etc/fstab
swapon -a
swapon -s
