#!/bin/bash -e

if [ -z "$2" ]; then
	echo Params: domain-name e-mail
	exit -1
fi

NAME=$1
EMAIL=$2

IMAGE="webvariants/nginx-certbot"
CONTAINER="rancher-nginx-certbot"

echo "Image: $IMAGE"

docker pull $IMAGE

set +e
RUNNING=$(docker inspect --format="{{ .State.Running }}" $CONTAINER 2> /dev/null)
set -e

if [ "$RUNNING" == "true" ]; then
	echo Stopping container...
	docker stop -t 1 ${CONTAINER}
fi

set +e
RUNNING=$(docker inspect --format="{{ .State.Running }}" $CONTAINER 2> /dev/null)
set -e

if [ "$RUNNING" == "false" ]; then
	echo Removing container...
	docker rm ${CONTAINER}
fi

docker run -d \
	--name $CONTAINER \
	--link rancher-server:rancher \
	-p 80:80 -p 443:443 \
	-e SERVICE_NAME=rancher \
	-e SERVICE_PORT=8080 \
	-e SERVER_NAME=$NAME \
	-e CERT_EMAIL=$EMAIL \
	--restart=unless-stopped \
	-v rancher-nginx-certbot:/etc/letsencrypt \
	$IMAGE
