#!/bin/bash

docker run \
	-d \
	--restart=always \
	-e "VIRTUAL_HOST=portainer" \
	-e "VIRTUAL_PORT=9000" \
	-l "traefik.port=9000" \
	--name portainer \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-v $PWD/data:/data \
	$@ \
	portainer/portainer
