#!/bin/bash

if [ -f "$1" ]; then
    echo "File already exists."
    exit
fi

touch $1

docker run \
	--rm \
	--read-only \
	--link mysql \
	-v $1:/dump.sql \
	--network mysql \
	mysql:5.7 \
	/bin/bash -c "mysqldump -h mysql -u root -proot ${2} > /dump.sql"
