#!/bin/bash
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

if [ ! -z "$WWW_DATA_UID" ]; then
	echo "www-data uid => ${WWW_DATA_UID}"
	usermod -u ${WWW_DATA_UID} www-data
	if [ ! -z "$WWW_DATA_GID" ]; then
		echo "www-data gid => ${WWW_DATA_GID}"
		groupmod -g ${WWW_DATA_GID} www-data
	fi
	chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2
fi

exec apache2 -DFOREGROUND
